//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinema> CinemaSet { get; set; }
        public virtual DbSet<Film> FilmSet { get; set; }
        public virtual DbSet<Session> SessionSet { get; set; }
        public virtual DbSet<Hall> HallSet { get; set; }
        public virtual DbSet<Cashier> CashierSet { get; set; }
        public virtual DbSet<Seat> SeatSet { get; set; }
        public virtual DbSet<Ticket> TicketSet { get; set; }
        public virtual DbSet<Booking> BookingSet { get; set; }
    }
}
